version: '2'
services:
  app:
    container_name: hn
    build: .
    image: reg.hcpss.org/headline-news/build
    volumes:
      - ./headline-news/dist:/app/dist
      - ./headline-news/src:/app/src
    user: node
    working_dir: /app
    ports:
      - 3000:3000
      - 3001:3001
    # command:
    #   - npm
    #   - build
    #   - "--production"
